---
- name: Install Proxmox VE on Debian 12 Bookworm
  hosts: katana
  become: yes
  vars:
    proxmox_hostname: "katana"
    proxmox_domain: "local"
    proxmox_fqdn: "{{ proxmox_hostname }}.{{ proxmox_domain }}"
    proxmox_ip: "{{ ansible_host }}"
    
  tasks:
    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted

    - name: Ensure hostname can be resolved to IP address
      block:
        - name: Verify hostname resolution
          command: getent hosts {{ proxmox_hostname }}
          register: hostname_check
          changed_when: false
          
        - name: Display hostname resolution result
          debug:
            msg: "Hostname {{ proxmox_hostname }} resolves to: {{ hostname_check.stdout }}"
            
        - name: Fail if hostname doesn't resolve to correct IP
          fail:
            msg: "Hostname {{ proxmox_hostname }} does not resolve to {{ proxmox_ip }}. Got: {{ hostname_check.stdout }}"
          when: proxmox_ip not in hostname_check.stdout

    - name: Add Proxmox VE repository
      block:
        - name: Add Proxmox VE repository to sources.list.d
          copy:
            content: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription\n"
            dest: /etc/apt/sources.list.d/pve-install-repo.list
            mode: '0644'
            
        - name: Download Proxmox VE repository GPG key
          get_url:
            url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
            dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
            mode: '0644'
            
        - name: Verify GPG key checksum
          stat:
            path: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
            checksum_algorithm: sha512
          register: gpg_key_stat
          
        - name: Fail if GPG key checksum doesn't match
          fail:
            msg: "GPG key checksum verification failed"
          when: gpg_key_stat.stat.checksum != "7da6fe34168adc6e479327ba517796d4702fa2f8b4f0a9833f5ea6e6b48f6507a6da403a274fe201595edc86a84463d50383d07f64bdde2e3658108db7d6dc87"

    - name: Download Proxmox VE post-install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/pve/post-pve-install.sh
        dest: /root/post-pve-install.sh
        mode: '0700' # Make it executable for root

    - name: Update repository and system packages
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes

    - name: Install Proxmox VE kernel
      apt:
        name: proxmox-default-kernel
        state: present
      register: kernel_install

    - name: Reboot to use Proxmox VE kernel
      reboot:
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: kernel_install.changed

    - name: Wait for system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300
      when: kernel_install.changed

    - name: Install Proxmox VE packages
      apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
          - chrony
        state: present
      register: pve_install

    - name: Configure postfix for local delivery only (non-interactive)
      debconf:
        name: postfix
        question: postfix/main_mailer_type
        value: "Local only"
        vtype: select
      when: pve_install.changed

    - name: Set postfix system mail name
      debconf:
        name: postfix
        question: postfix/mailname
        value: "{{ proxmox_fqdn }}"
        vtype: string
      when: pve_install.changed

    - name: Remove Debian default kernel
      apt:
        name:
          - linux-image-amd64
          - "linux-image-6.1*"
        state: absent
        purge: yes
      register: kernel_removal

    - name: Update GRUB configuration
      command: update-grub
      when: kernel_removal.changed

    - name: Remove os-prober package (recommended)
      apt:
        name: os-prober
        state: absent
        purge: yes

    - name: Display Proxmox VE access information
      debug:
        msg:
          - "Proxmox VE installation completed successfully!"
          - "For next steps, refer to the post-installation guide:"
          - "https://github.com/nielsmaerten/katana/blob/main/200-install-proxmox/POST_INSTALL.md"