# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
version: "1"

global:
  schedule-defaults:
    permission: "system"
    lock-wait: "5h"

opencloud:
  status-file: "/root/resticprofile-opencloud.status.json"
  repository: "rclone:target-opencloud:"
  password-file: "/root/.restic-password.txt"
  forget:
    prune: true
    keep-daily: 90
    keep-hourly: 48
    schedule:
      - "05:39"
  backup:
    one-file-system: true
    option:
      - "-o rclone.transfers=4"
    source:
      - "/tank/opencloud"
    exclude-caches: true
    exclude-if-present:
      - ".nobackup"
    send-before:
      - url: "{{ resticprofile_opencloud_url_before }}"
    send-after:
      - url: "{{ resticprofile_opencloud_url_after }}"
    send-after-fail:
      - url: "{{ resticprofile_opencloud_url_fail }}"
    # Schedule runs every 15 minutes
    schedule:
      - "*:0/15"
  check:
    schedule:
      - "Wed 01:00"
    read-data-subset: "10%"

paperless:
  status-file: "/root/resticprofile-paperless.status.json"
  repository: "rclone:target-paperless:"
  password-file: "/root/.restic-password.txt"
  forget:
    prune: true
    keep-daily: 30
    keep-weekly: 52
    schedule:
      - "0/4:20"
  backup:
    one-file-system: true
    option:
      - "-o rclone.transfers=4"
    source:
      - "/tank/paperless"
    exclude-caches: true
    exclude:
      - "/**/log/**"
    exclude-if-present:
      - ".nobackup"
    send-before:
      - url: "{{ resticprofile_paperless_url_before }}"
    send-after:
      - url: "{{ resticprofile_paperless_url_after }}"
    send-after-fail:
      - url: "{{ resticprofile_paperless_url_fail }}"
    schedule:
      - "0/2:00"
  check:
    schedule:
      - "Mon 01:00"
    read-data-subset: "10%"

immich:
  status-file: "/root/resticprofile-immich.status.json"
  repository: "rclone:target-immich:"
  password-file: "/root/.restic-password.txt"
  forget:
    prune: true
    keep-daily: 30
    keep-monthly: 12
    keep-yearly: 10
    schedule:
      - "4:20"
  backup:
    one-file-system: true
    option:
      - "-o rclone.transfers=4"
    source:
      - "/tank/immich"
    exclude-caches: true
    exclude-if-present:
      - ".nobackup"
    send-before:
      - url: "{{ resticprofile_immich_url_before }}"
    send-after:
      - url: "{{ resticprofile_immich_url_after }}"
    send-after-fail:
      - url: "{{ resticprofile_immich_url_fail }}"
    schedule:
      - "0/6:30"
  check:
    schedule:
      - "Sat 01:00"
    read-data-subset: "5%"

katana-backup:
  status-file: "/root/resticprofile-katana-backup.status.json"
  repository: "rclone:target-katana-backup:"
  password-file: "/root/.restic-password.txt"
  forget:
    prune: true
    keep-daily: 7
    schedule:
      - "0/12:45"
  backup:
    one-file-system: true
    source-base: "/"
    exclude-if-present:
      - ".nobackup"
    option:
      - "-o rclone.transfers=4"
    source:
      - "/tank/pbs-datastore"
      - "/mnt/etc/pve"
      - "/mnt/etc/network/interfaces"
      - "/mnt/etc/hosts"
      - "/mnt/etc/hostname"
      - "/mnt/etc/resolv.conf"
      - "/mnt/etc/ssh"
      - "/mnt/etc/restic"
      - "/mnt/etc/cron.*"
    exclude-caches: true
    exclude:
      - "/**/tmp/**"
      - "/**/cache/**"
    send-before:
      - url: "{{ resticprofile_katana_backup_url_before }}"
    send-after:
      - url: "{{ resticprofile_katana_backup_url_after }}"
    send-after-fail:
      - url: "{{ resticprofile_katana_backup_url_fail }}"
    schedule:
      - "0/4:15"
  check:
    schedule:
      - "Wed 02:02"
    read-data-subset: "10%"

groups:
  default:
    - "paperless"
    - "katana-backup"
    - "immich"
    - "opencloud"
