# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
version: "1"

global:
  schedule-defaults:
    permission: "system"
    lock-wait: "5h"

paperless:
  status-file: "/root/resticprofile-paperless.status"
  repository: "rclone:target-paperless:"
  password-file: "/root/.restic-password.txt"
  forget:
    prune: true
    keep-daily: 30
    keep-weekly: 52
    schedule:
      - "01:00"
  backup:
    one-file-system: true
    source:
      - "/tank/paperless"
    exclude-caches: true
    exclude:
      - "/**/log/**"
    send-after:
      - url: "https://ntfy.sh/katana"
        method: "POST"
        body: "Paperless backup completed successfully."
    send-after-fail:
      - url: "https://ntfy.sh/katana"
        method: "POST"
        body: "Paperless backup failed."
    schedule:
      - "01:01" # Will start after the retention job and wait for it to finish
  check:
    schedule:
      - "Mon 01:02"
    read-data-subset: "10%"

katana-backup:
  status-file: "/root/resticprofile-katana-backup.status"
  repository: "rclone:target-katana-backup:"
  password-file: "/root/.restic-password.txt"
  forget:
    prune: true
    keep-daily: 7
    schedule:
      - "02:00"
  backup:
    one-file-system: true
    source-base: "/"
    source:
      - "/tank/pbs-datastore"
      - "/mnt/etc/pve"
      - "/mnt/etc/network/interfaces"
      - "/mnt/etc/hosts"
      - "/mnt/etc/hostname"
      - "/mnt/etc/resolv.conf"
      - "/mnt/etc/ssh"
      - "/mnt/etc/restic"
      - "/mnt/etc/cron.*"
    exclude-caches: true
    exclude:
      - "/**/tmp/**"
      - "/**/cache/**"
    send-after:
      - url: "https://ntfy.sh/katana"
    send-after-fail:
      - url: "https://ntfy.sh/katana"
    schedule:
      - "02:01"
  check:
    schedule:
      - "Wed 02:02"
    read-data-subset: "10%"

groups:
  default:
    - "paperless"
    - "katana-backup"
